### ISSUE TITLE
Cannot find module 'strtok3/lib/type' or its corresponding type declarations.

### ISSUE THREAD

**Issue by fabpin** [Borewit/music-metadata#606] opened 2020-09-03 02:39 UTC
Hi, good night, already i´m having this issue with the version of music-metadata 4.8.4, somebody can help me, i would appreciate that, adjunct evidence:

![Evidence 1](https://user-images.githubusercontent.com/8019419/92065157-bc4e9300-ed64-11ea-8a74-5c6528598071.png)

**Comment by Borewit** [comment] 2020-09-03 07:22
Duplicate of #487 

Just update your dependencies.

**Closed** 2020-09-03 07:22 UTC
