### ISSUE TITLE
Cannot find module 'strtok3/core' or its corresponding type declarations.

### ISSUE THREAD

**Issue by d-sphinx** [Borewit/music-metadata#1373] opened 2022-10-25 17:22 UTC
"music-metadata": "^8.1.0"

[{
	"resource": "/c:/_WORK/link_metadata/node_modules/music-metadata/lib/apev2/APEv2Token.d.ts",
	"owner": "typescript",
	"code": "2307",
	"severity": 8,
	"message": "Cannot find module 'strtok3/core' or its corresponding type declarations.",
	"source": "ts",
	"startLineNumber": 2,
	"startColumn": 27,
	"endLineNumber": 2,
	"endColumn": 41
}]

APEv2Token.d.ts tries to import { IGetToken } from 'strtok3/core';

There is no 'core' file or dir in node_modules/strtok3

**Comment by Borewit** [comment] 2022-10-25 17:25
Yes there is: 

https://github.com/Borewit/strtok3/blob/91791f8f2ef80f905bdc0bc1088fd96ff2076ae9/package.json#L42

Problem is that your environment lacks proper ESM support, duplicate of #1217

**Comment by d-sphinx** [comment] 2022-10-25 17:32
> Yes there is:
> 
> https://github.com/Borewit/strtok3/blob/91791f8f2ef80f905bdc0bc1088fd96ff2076ae9/package.json#L42
> 
> Problem is that your environment lacks proper ESM support, duplicate of #1217

How do I fix it? My node is v14.20.1 (latest in 14 branch) - is this causes a problem?

**Comment by Borewit** [comment] 2022-10-25 17:52
Node version should be `^14.13.1 || >=16.0.0"`, so that is fine.

Tests are passing against the latest Node v14: 

https://github.com/Borewit/music-metadata/blob/master/.github/workflows/nodejs-ci.yml#L50

Maybe upgrade your TypeScript dev dependencies, seems on that level as it complaining about typings.

**Comment by bradleat** [comment] 2022-11-10 02:11
I think the issue for most build tools (including the typescript compiler in the default configuration), is that the import should be to `strtok3/lib/core`

adding this to the compilerOptions of the tsconfig works:

```
"paths": {
        "strtok3/core": ["./node_modules/strtok3/lib/core"]
      }
```

or use `moduleResolution: "node16"` in the same place


The problem with the latter method is that it's incompatible with other tools and libraries at the moment.

**Comment by Borewit** [comment] 2022-11-11 07:33
Thanks for sharing your experience @bradleat

**Closed** 2023-01-05 12:07 UTC
Labels: duplicate
