### ISSUE TITLE
wma: embedded picture data is accessible via the common metadata interface

### ISSUE THREAD

**Issue by jirihajek** [Borewit/music-metadata#57] opened 2018-02-28 15:10 UTC
I haven't studied the file in details and so I'm not sure how serious the error is, but similarly to #56, I suppose that it should be possible to at least read the rest of the tag?

[sample_problem.zip](https://github.com/Borewit/music-metadata/files/1767576/sample_problem.zip)

**Comment by Borewit** [comment] 2018-03-02 07:09
Sorry @jirihajek, I was not able to reproduce your issue.

**Comment by jirihajek** [comment] 2018-03-02 12:12
Sorry, my fault, the file actually is parsed correctly. The only problem there is that the resulting picture contains empty 'data' field. I guess that this might be a bug?

**Comment by Borewit** [comment] 2018-03-02 20:29
ASF parser could be written better, however. bug should be fixed in [v0.9.7](https://github.com/Borewit/music-metadata/releases/tag/v0.9.7).

**Closed by Borewit** 2018-03-02 20:29 UTC
Labels: bug
