### ISSUE TITLE
Hope to support tag writing

### ISSUE THREAD

**Issue by Linkontoask** [Borewit/music-metadata#714] opened 2020-12-31 15:14 UTC
**Feature Request**

I hope that after parsing, I can delete and modify the metadata and return the processed data.
I don't know if this is difficult. When I read your code, I found that a lot of things have been done, such as parsed data. (I guess if I just need to replace the data in the right place)

demo

```javascript
import { parseBuffer } from 'music-metadata'
import { writeFile } from 'fs'
parseBuffer(buffer)
  .then(data => data.updateTag('COMM', Buffer.from('I am a comment', 'utf-8')))
  .then(buffer => {
      writeFile('comment.mp3', buffer, () => {})
  })
```

**Comment by Borewit** [comment] 2021-01-04 18:55
Duplicate of #10. It is not so easy, it is a lot of work, and I think it will make the component a lot heavier. But you are right, a lot of things can be reused.

**Comment by Linkontoask** [comment] 2021-01-05 02:13
I think you have replied in other issues that you do not intend to support tag writing. Unfortunately, I don’t know much about this technology, otherwise I can provide some help.

**Comment by subframe7536** [comment] 2022-12-06 13:58
maybe [node-tablig-sharp](https://github.com/benrr101/node-taglib-sharp) can help

**Comment by Borewit** [comment] 2023-01-05 12:04
I am not planning to work on this enhancement

**Closed by Borewit** 2023-01-05 12:05 UTC
Labels: enhancement, de-scoped
