### ISSUE TITLE
does not provide an export named 'parseFile' 

### ISSUE THREAD

**Issue by Yuban32** [Borewit/music-metadata#1859] opened 2023-09-26 03:41 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### music-metadata version

music-metadata 8.1.4

### JavaScript module eco system

ECMAScript modules (ESM), music-medata ≥ version 8

### Current Behavior

I used it on Vite and followed the example :
import { parseFile } from 'music-metadata';
import { inspect } from 'util';

(async () => {
  try {
    const metadata = await parseFile('../music-metadata/test/samples/MusicBrainz - Beth Hart - Sinner\'s Prayer [id3v2.3].V2.mp3');
    console.log(inspect(metadata, { showHidden: false, depth: null }));
  } catch (error) {
    console.error(error.message);
  }
})();
 the browser console provided feedback on Uncaught SyntaxError: The requested module '/node_ Modules/. vite/deps/music metadata. js? T=1695699146826&v=47748d9c 'does not provide an export named' parseFile '

### Expected Behavior

I just want to use this library normally

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by Borewit** [comment] 2023-10-22 10:18
Duplicate of #1425

**Closed by Borewit** 2023-10-22 10:18 UTC
Labels: duplicate

**Comment by Yuban32** [comment] 2023-11-13 02:30
> Duplicate of #1425

thanks bro
