### ISSUE TITLE
parseFile Not working 

### ISSUE THREAD

**Issue by prakashkattoju** [Borewit/music-metadata#1259] opened 2022-08-29 07:09 UTC
export 'parseFile' (imported as 'parseFile') was not found in 'music-metadata' (possible exports: orderTags, parseBuffer, parseFromTokenizer, parseStream, ratingToStars, scanAppendingHeaders, selectCover)

**Comment by Borewit** [comment] 2022-09-05 11:22
Which version of music-metadata, are you using it in Node.js or client side?

**Comment by prakashkattoju** [comment] 2022-09-06 06:59
installed the latest version and am using it in node.js for the audio file meta data ( eg: for song name, artist )

**Comment by julianpoemp** [comment] 2022-09-06 10:27
similar issue in my case: somehow I can't import the parseFile method from music-metadata:

**Code**:
````typescript
import {parseFile} from 'music-metadata';
...
const metadata = await parseFile(path);
````

**Error**:
````
/Users/<user>/repos/<project>/node_modules/@nrwl/js/src/executors/node/node-with-require-overrides.js:16
        return originalLoader.apply(this, arguments);
                              ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/<user>/repos/<project>/node_modules/music-metadata/lib/index.js from /Users/<user>/repos/<project>/dist/apps/api/main.js not supported.
Instead change the require of index.js in /Users/<user>/repos/<project>/dist/apps/api/main.js to a dynamic import() which is available in all CommonJS modules.
````

I used music-metadata in a NestJS project (NodeJS), version v8.0.1. Because it doesn't work for me, I went back to v7.12.6

**Comment by Borewit** [comment] 2022-09-06 11:03
@julianpoemp [music-metadata](https://github.com/Borewit/music-metadata) version 8 is a pure ES-Module (so not  CommonJS module), therefor attempts rewriting `import` to `require` will fail.

**Comment by subframe7536** [comment] 2022-09-18 03:41
similar issue when using [electron+vite](https://github.com/electron-vite/electron-vite-vue)
v8.0.1
### usage
```ts
import { parseFile } from 'music-metadata'
import { resolve } from 'path'
const metaInfo = await parseFile(resolve(dir, file.relativePath))
```
### error
```
'parseFile' is not exported by node_modules/music-metadata/lib/core.js, imported by electron/service/parseMetadata/index.ts
```

### tsconfig
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "node",
    "importHelpers": true,
    "jsx": "preserve",
    "esModuleInterop": true,
    ...
  }
}
```

**Comment by Borewit** [comment] 2022-09-18 10:23
@subframe7536, electron as kind of mix between Node.js ([main](https://www.electronjs.org/docs/latest/tutorial/process-model#the-main-process)) & Chromium ([renderer](https://www.electronjs.org/docs/latest/tutorial/process-model#the-renderer-process)). 
It looks like your import is following the `default` path instead of the `node` path in the [conditional exports](https://nodejs.org/api/packages.html#conditional-exports), which includes the Node.js specific function `parseFile()`:
https://github.com/Borewit/music-metadata/blob/530d3cd3dcb4ed39bc681c7ca9a5a6c8b12a6e18/package.json#L14-L19

First thing I would ensure that import is done by the [main](https://www.electronjs.org/docs/latest/tutorial/process-model#the-main-process). Best design in my opinion, to perform parsing on the backend ([main](https://www.electronjs.org/docs/latest/tutorial/process-model#the-main-process)).

If that does not resolve your issue, you probably should look for your answer within the Electron community. Let me know if you got this one sorted out.

Alternatively you could choose to use the CommonJS version of music-metadata, version 7.x.

**Comment by subframe7536** [comment] 2022-09-18 10:55
Sorry for not providing complete information. I did it in main process.

and now i choose to get buffer using `fs` and use `parseBuffer` to get metadata and it works😂 
- using `fs` to get readstream and `parseStream` seem to fail to parse `sampleRate`?
```ts
const metaInfo = await parseBuffer(new Uint8Array(read(path, 'buffer')))
```

**Comment by midmarch** [comment] 2022-09-19 08:54
So you have imported `"default": "./lib/core.js" ` which defines `parseBuffer` & `parseStream`. 
Via the main process, as this is comparable to Node.js, you should be automatically importing `"node": "./lib/index.js"`, which defines `parseFile`. 

I you like I can also add an explicit sub-path export, so you can maybe enforce importing Node.js functions. 

> and now i choose to get buffer using `fs-jetpack` and use `parseBuffer` to get metadata and it worksjoy
> 
> * using `fs` to get readstream and `parseStream` seem to fail to parse `sampleRate`?
> 
> ```ts
> const metaInfo = await parseBuffer(new Uint8Array(read(path, 'buffer')))
> ```

This is a vague description, please open an issue with something I can reproduce easily with a sample file.
You should be able to parse a stream like this.

```js
const stream = fs.createReadStream(filePath);
return mm.parseStream(stream);
 ```
Note that this can be significantly slower then `parseFile()`, as streams cannot seek (ignore), they have read all the the data.

Using buffer is even worse, you have to read the entire audio file plus you have to keep the entire audio file in memory.

**Comment by Borewit** [comment] 2022-09-19 08:55
So you have imported `"default": "./lib/core.js" ` which defines `parseBuffer` & `parseStream`. 
Via the main process, as this is comparable to Node.js, you should be automatically importing `"node": "./lib/index.js"`, which defines `parseFile`. 

I you like I can also add an explicit sub-path export, so you can maybe enforce importing Node.js functions. 

> and now i choose to get buffer using `fs-jetpack` and use `parseBuffer` to get metadata and it worksjoy
> 
> * using `fs` to get readstream and `parseStream` seem to fail to parse `sampleRate`?
> 
> ```ts
> const metaInfo = await parseBuffer(new Uint8Array(read(path, 'buffer')))
> ```

This is a vague description, please open an issue with something I can reproduce easily with a sample file.
You should be able to parse a stream like this.

```js
const stream = fs.createReadStream(filePath);
return mm.parseStream(stream);
 ```
Note that this can be significantly slower then `parseFile()`, as streams cannot seek (ignore), they have read all the the data.

Using buffer is even worse, you have to read the entire audio file plus you have to keep the entire audio file in memory.

**Comment by midmarch** [comment] 2022-09-19 12:52
> esm can't be used in electron|

That's what I thought, but since you have been able to use some function I thought maybe something changed.
 v7.13.0 is functional identical and up to date, so that's perfectly fine for now.

**Comment by Borewit** [comment] 2022-09-19 12:52
That's what I thought, but since you have been able to use some function I thought maybe something changed.
 v7.13.0 is functional identical and up to date, so that's perfectly fine for now.

**Comment by Borewit** [comment] 2022-09-20 10:59
I close this issue, as in either case, appears to me as incompatibility issues with ESM modules in the source project environment.

**Closed** 2022-09-26 09:14 UTC
Labels: question, wontfix
