### ISSUE TITLE
FourCC contains invalid characters: 00 00 00 00

### ISSUE THREAD

**Issue by ozelot379** [Borewit/music-metadata#387] opened 2019-12-29 10:20 UTC
**Bug description**
On some iTunes purchased movies (m4v), I get `FourCC contains invalid characters: 00 00 00 00`

I can patch/fix this by `return "    ";` (4x spaces) instead throwing an `Error` in https://github.com/Borewit/music-metadata/blob/e0725b95494e9107f8498e9642f85fff3f84a501/lib/common/FourCC.ts#L16

But how to fix this really, I don't know

**Expected behavior**
I dont' know, whether it's possible to parse drm protected tracks, but I think at least the tags and the duration should work.

**Audio file demonstrating the problem**
Not possible due copyright

**Comment by Borewit** [comment] 2019-12-29 10:56
Thanks for creating this issue @ozelot379.

It is important to determine if the FourCC actually is `00 00 00 00` **or** if the issue is caused because the FourCC is decoded from a wrong offset.

**Comment by ozelot379** [comment] 2020-01-12 16:35
isn't necessary to fix this bug - I can skip these few files for my use case, if an exception is occured

**Comment by Borewit** [comment] 2020-01-12 19:49
I would like address this issue

**Comment by ozelot379** [comment] 2020-01-28 16:06
> It is important to determine if the FourCC actually is 00 00 00 00 or if the issue is caused because the FourCC is decoded from a wrong offset.

Can I figure out this for you, since you haven't the file?

**Comment by Borewit** [comment] 2020-01-28 16:46
Sure, but it requires to debug the code.

Is the `0000` used as an atom ID? If so, is the atom valid? If not, to what does the `0000` belongs to.

You can set `DEBUG=*` or `DEBUG=-mocha:*,*` if you debug via a unit test to get some verbose output.

Alternatively you can pass me the file via a private channel, so I can investigate. I will only use the file to investigate this specific issue. I don't expect this would be in violation with the copyright.

Cars are also composed of copyrighted material, it is not forbidden to bring them to a garage.

**Comment by qcasey** [comment] 2020-02-16 20:50
@Borewit are you still interested in debugging? I'm experiencing both this issue and #388 and can send you the files privately if that helps. 

Debugging this myself is outside my wheelhouse, I am also skipping the files in the meantime.

**Comment by ozelot379** [comment] 2020-02-16 20:58
thanks, if you could these
unfordabely I had made no progress to debug self

**Comment by Borewit** [comment] 2020-02-17 07:16
> @Borewit are you still interested in debugging? I'm experiencing both this issue and #388 and can send you the files privately if that helps.

I do, you can reach me via [discord](https://discord.gg/KyBr6sb).  I will be online ~18:30 UTC.

**Comment by Borewit** [comment] 2020-02-18 07:36
The following is based on the sample provided by @qcasey (very much appreciated).

This error is caused by a list item atom of moov.udta.meta.ilst, with the type set to` 0x0000`.

The `moov.udta.meta.keys` atom atom can list the number of sub items, which could prevent the parser hitting the _0000-type-atom_.
But there is no `moov.udta.meta.keys` atom present, which is mandatory of the structure described [here](https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/Metadata/Metadata.html#//apple_ref/doc/uid/TP40000939-CH1-SW8). 

However [that structure applies](https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/Metadata/Metadata.html#//apple_ref/doc/uid/TP40000939-CH1-SW8) if the metadata handler atom specifies type=`mdta` , this case the type =`soun`.

**The easy way** 

The easy way would be to allow 0x0000 is a valid [Four-CC](https://www.fourcc.org/fourcc.php) value. The Four-CC is currently programmed as [shared token](https://github.com/Borewit/strtok3#method-tokenizerreadtoken) with other formats. 0x0000 is also used to indicate garbage, empty data. In other words, allowing 0000 is a four-cc breaks other things.

**Comment by Borewit** [comment] 2020-02-18 20:06
Fixed in [v6.3.4](https://github.com/Borewit/music-metadata/releases/tag/v6.3.4)

**Comment by ozelot379** [comment] 2020-02-19 17:53
I still get the same error with v6.3.4

```
UnhandledPromiseRejectionWarning: Error: FourCC contains invalid characters: 00 00 00 00
    at Object.get (node_modules/music-metadata/lib/common/FourCC.js:14:19)
    at SampleDescriptionTable.get (node_modules/music-metadata/lib/mp4/AtomToken.js:220:46)
    at StsdAtom.get (node_modules/music-metadata/lib/mp4/AtomToken.js:241:57)
    at FileTokenizer.readToken (node_modules/strtok3/lib/AbstractTokenizer.js:27:22)
    at async MP4Parser.parseAtom_stsd (node_modules/music-metadata/lib/mp4/MP4Parser.js:380:22)
    at async Function.readAtom (node_modules/music-metadata/lib/mp4/Atom.js:25:9)
    at async Atom.readAtoms (node_modules/music-metadata/lib/mp4/Atom.js:36:30)
    at async Function.readAtom (node_modules/music-metadata/lib/mp4/Atom.js:25:9)
    at async Atom.readAtoms (node_modules/music-metadata/lib/mp4/Atom.js:36:30)
    at async Function.readAtom (node_modules/music-metadata/lib/mp4/Atom.js:25:9)
```

**Comment by Borewit** [comment] 2020-02-19 19:39
> I still get the same error with v6.3.4
> 
> ```
> UnhandledPromiseRejectionWarning: Error: FourCC contains invalid characters: 00 00 00 00
>     at Object.get (node_modules/music-metadata/lib/common/FourCC.js:14:19)
>     at SampleDescriptionTable.get (node_modules/music-metadata/lib/mp4/AtomToken.js:220:46)
>     at StsdAtom.get (node_modules/music-metadata/lib/mp4/AtomToken.js:241:57)
>     at FileTokenizer.readToken (node_modules/strtok3/lib/AbstractTokenizer.js:27:22)
>     at async MP4Parser.parseAtom_stsd (node_modules/music-metadata/lib/mp4/MP4Parser.js:380:22)
>     at async Function.readAtom (node_modules/music-metadata/lib/mp4/Atom.js:25:9)
>     at async Atom.readAtoms (node_modules/music-metadata/lib/mp4/Atom.js:36:30)
>     at async Function.readAtom (node_modules/music-metadata/lib/mp4/Atom.js:25:9)
>     at async Atom.readAtoms (node_modules/music-metadata/lib/mp4/Atom.js:36:30)
>     at async Function.readAtom (node_modules/music-metadata/lib/mp4/Atom.js:25:9)
> ```

That is in the [Sample Description Atom ('stsd')](https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html#//apple_ref/doc/uid/TP40000939-CH204-25691), in the dataFormat field, or misread of that field:

>Important: When parsing sample descriptions in the ‘stsd’ atom, be aware of the sample description size value in order to read each table entry correctly. Some sample descriptions terminate with four zero bytes that are not otherwise indicated.

That file would be of great value @ozelot379, can you reach out in [chat](https://discord.gg/KyBr6sb)?

**Closed** 2020-05-26 20:00 UTC
Labels: bug, cannot reproduce
