### ISSUE TITLE
Cannot get playtime from some mp3's

### ISSUE THREAD

**Issue by mycoboco** [Borewit/music-metadata#39] opened 2017-09-05 06:16 UTC
I have six mp3's from which `music-metadata` cannot extract playtimes, and attach two of them expecting they represents others. They are handled by `mp3-duration` with no problems.

[01.mp3.zip](https://github.com/Borewit/music-metadata/files/1276277/01.mp3.zip)
[02.mp3.zip](https://github.com/Borewit/music-metadata/files/1276279/02.mp3.zip)

**Comment by Borewit** [comment] 2017-09-06 08:04
Issue is caused by multiple ID3v2 headers.

**Comment by Borewit** [comment] 2017-09-06 08:18
Fixed in [v0.8.3](https://github.com/Borewit/music-metadata/releases/tag/v0.8.3)

**Closed by Borewit** 2017-09-06 08:18 UTC
Labels: bug, enhancement
