### ISSUE TITLE
mp3 parsing results in 'RangeError: Index out of range'

### ISSUE THREAD

**Issue by jirihajek** [Borewit/music-metadata#56] opened 2018-02-28 15:06 UTC
While the error is possibly valid (not sure whether a PRIV WMP frame is correct or not), I wonder whether there's a way to access other fields, when only one is invalid? Thanks!

[x.zip](https://github.com/Borewit/music-metadata/files/1767562/x.zip)

**Comment by Borewit** [comment] 2018-03-01 21:14
Issues was caused by an illegal ID3v2.3 PRIV:PeakValue tag, containing no data.

Note that this MP3 file also contains an APEv2 header tag.
That header is not meant for an MP3 file.

**Comment by Borewit** [comment] 2018-03-02 08:09
Fixed in [v0.9.6](https://github.com/Borewit/music-metadata/releases/tag/v0.9.6)

**Closed by Borewit** 2018-03-02 08:09 UTC
Labels: bug

**Comment by jirihajek** [comment] 2018-03-02 09:25
Thanks for the quick fix!

However, from a general point of view, have you considered some kind of 'ignore errors' mode? What I mean is that this isn't uncommon -- an application writes some less important field (as PRIV::PeakValue) incorrectly, or music-metadata isn't able to read it, but the result is that even perfectly readable important fields (as Title, Artist, ...) aren't available then. Maybe the tag could be read without an error, but the resulting metadata object could contain an array 'warnings' with something like: "Priv::PeakValue": "incomplete"?

**Comment by Borewit** [comment] 2018-03-02 10:42
I like the idea of returning warnings, I did thought about it indeed, and in fact on multiple places in the code there are _ToDo_ comments indicating the warning should be captured. I created an issue to address this: #60.

In general the parser aims to continue parsing, despite the ugliness it may has to deal with along the way. At the same time, I am a firm believer in the [fail fast principle](http://enterprisecraftsmanship.com/2015/09/15/fail-fast-principle/). If something nasty happens in the code, let it crash.

**Comment by jirihajek** [comment] 2018-03-02 11:46
I agree with fail fast in general. In this particular case however, due to variety of apps writing tags, there are necessarily buggy tags written. And then, without some fault tolerant code, all fields are presented as empty (Title, Artist, ...), which looks like a bug when compared to other applications -- including basic OS layers like Windows Explorer.

Anyway, nice to hear that you have plans for this!
