### ISSUE TITLE
Writing metadata

### ISSUE THREAD

**Issue by HermanLederer** [Borewit/music-metadata#792] opened 2021-04-10 16:36 UTC
I really like the variety of metadata formats this package understands, but as far as I know it can only read tags, but does not write them. Could you please implement the ability to write tags to files as well?

I have found a package that writes mp3 metadata called node-id3, but it only works with id3 tags, I am probably going to temporarily use it and limit my applications' functionality to just mp3, but would be happy to use music-metadata instead as soon as it is possible.

**Comment by Borewit** [comment] 2021-04-12 11:13
Duplicate of #10

**Comment by Borewit** [comment] 2021-04-12 11:17
Please use issue #714.

**Closed by Borewit** 2021-04-12 11:17 UTC
Labels: duplicate
