### ISSUE TITLE
[Question] Is it possible to add metadata to files?

### ISSUE THREAD

**Issue by staniel359** [Borewit/music-metadata#1455] opened 2022-12-19 11:02 UTC
Hello.
I was wondering if you library can read metadata, can it also write it?

**Comment by Borewit** [comment] 2022-12-19 11:52
Sorry, that is not possible.

Duplicate of #792, #714, #10

**Closed** 2022-12-19 11:53 UTC
Labels: duplicate, question

**Comment by staniel359** [comment] 2022-12-19 12:37
@Borewit Too bad.
Sorry for duplicate.
