### ISSUE TITLE
CommonJS

### ISSUE THREAD

**Issue by biologyscience** [Borewit/music-metadata#1364] opened 2022-10-24 10:01 UTC
Just wanted ask if there is a update to the package, will there be a CommonJS version of it as well ? If so, will it be in the **7.x** versions ?

**Comment by Borewit** [comment] 2022-10-24 10:04
Duplicate of #1217, yes version 7.x is the latest CJS version. No difference in functionality with version 8.x other then that is an ESM module. Not sure how I will deal with this in the future.

**Closed by Borewit** 2022-10-24 10:04 UTC
Labels: duplicate, question
