### ISSUE TITLE
Field values containing slash character are split

### ISSUE THREAD

**Issue by admiraltoast** [Borewit/music-metadata#1073] opened 2022-03-31 20:14 UTC
**Bug description**
Could reproduce with genre and track artist fields.
If a field value contains a slash, without trailing spaces, the string is split.
Especially troublesome with track artists (e.g. "AC/DC")

**Expected behavior**
No value should be split by slash character

**Comment by Borewit** [comment] 2022-04-01 17:34
Can you provide a sample file @admiraltoast?

**Comment by admiraltoast** [comment] 2022-04-01 18:52
Sure thing!

I also checked with flac (vorbis comment) file where it doesn't happen (i.e. everything is parsed as a single string).
But with Mp3 (ID3v2.3) I could see that the following fields get split:

- artist (artist field itself contains part before slash, artists array contains both parts as single elements in array)
- composer
- genre

I used some dummy sample file so I don't commit copyright infringement but the tags are set so you can easily reproduce. 
[sample2.mp3.zip](https://github.com/Borewit/music-metadata/files/8400206/sample2.mp3.zip)

**Comment by Borewit** [comment] 2022-04-02 09:46
Duplicate of issue #52
Another similar issue: https://github.com/beetbox/mediafile/issues/21

The separation between artists decoded using '/' is in line with the specification: https://id3.org/id3v2.3.0#line-455  

So "AC/DC" is an artist name you cannot specify without resulting in this kind of misinterpretations. 

If you use the ID3v2.4 instead, you no longer have that constraint.

**Closed by Borewit** 2022-04-02 09:46 UTC
Labels: user input required

**Comment by admiraltoast** [comment] 2022-04-03 18:25
Thanks for the reply, especially the specs :)
