### ISSUE TITLE
Unable t import the lib

### ISSUE THREAD

**Issue by lordkyle0** [Borewit/music-metadata#1352] opened 2022-10-20 13:30 UTC
I Sir,

I get this error when try to import the library

Error: While trying to resolve module `music-metadata` from file `D:\ReactNative\Projects\JoTune\UI\NduleAfrik\screens\library\DownloadScreen.js`, the package `D:\ReactNative\Projects\JoTune\UI\NduleAfrik\node_modules\music-metadata\package.json` **was successfully found. However, this package itself specifies a `main` module field that could not be resolved** (`D:\ReactNative\Projects\JoTune\UI\NduleAfrik\node_modules\music-metadata\index`. I**ndeed, none of these files exist:**$

Metro bundle can't read the package. The package version is : 8.1.0

**Comment by Borewit** [comment] 2022-10-23 09:56
If you are looking from a CJS module you should use version 7, and not version 8 which is ESM.
Duplicate of #1218.

**Closed by Borewit** 2022-10-23 09:56 UTC
Labels: duplicate
