### ISSUE TITLE
Cannot find module 'strtok3/core' or its corresponding type declarations

### ISSUE THREAD

**Issue by arnab** [Borewit/music-metadata#1708] opened 2023-05-20 16:20 UTC
### Has the question been asked before?

- [X] I have searched the existing issues

### Question

I am trying to use this library from a Typescript function (running under Node.js 18 environment) deployed as a [Firebase function](https://firebase.google.com/docs/functions).

Here is what I have (`package.json` has `"music-metadata": "^8.1.4"`):

```typescript
import axios from "axios";
import * as mm from "music-metadata";

const response = await axios.get(urlString, {responseType: "arraybuffer"});
const buffer = Buffer.from(response.data);
const metadata = await mm.parseBuffer(buffer, contentType);
Logger.info(`Parsed audio metadata: ${JSON.stringify(metadata)}`);
```

TS is failing to compile with:

```
node_modules/music-metadata/lib/apev2/APEv2Token.d.ts:2:27 - error TS2307: Cannot find module 'strtok3/core' or its corresponding type declarations.

2 import { IGetToken } from 'strtok3/core';
                            ~~~~~~~~~~~~~~

node_modules/music-metadata/lib/core.d.ts:3:26 - error TS2307: Cannot find module 'strtok3/core' or its corresponding type declarations.

3 import * as strtok3 from 'strtok3/core';
                           ~~~~~~~~~~~~~~

node_modules/music-metadata/lib/core.d.ts:5:27 - error TS2307: Cannot find module 'strtok3/core' or its corresponding type declarations.

5 export { IFileInfo } from 'strtok3/core';
                            ~~~~~~~~~~~~~~

[9:18:09 AM] Found 3 errors. Watching for file changes.
```

What am I missing?

**Comment by arnab** [comment] 2023-05-20 16:24
This error goes away if I use the last major version of this library:

```
"music-metadata": "^7.13.4"
```

Is there something I need to do to use the latest 8.x version in a TS/Node.js 18 environment?

**Comment by Borewit** [comment] 2023-05-23 06:07
Duplicate of #1373

**Closed by Borewit** 2023-05-23 06:07 UTC
Labels: duplicate
